CREATE TABLE "account" (
  "user_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "user_name" varchar(255) NOT NULL,
  "email" varchar(255) UNIQUE NOT NULL,
  "password_hashed" varchar(255) NOT NULL,
  "user_type" smallint NOT NULL,
  "is_2fa_enabled" bool NOT NULL DEFAULT (false),
  "totp_secret_encrypted" varchar,
  "passkey_enabled" bool NOT NULL DEFAULT (false),
  "is_blocked" bool NOT NULL DEFAULT (false),
  "email_verified" bool NOT NULL DEFAULT (false),
  "created_at" timestamptz DEFAULT (now()),
  "updated_at" timestamptz DEFAULT (now())
);

CREATE TABLE "totp_backup_code" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "user_id" bigint NOT NULL,
  "code_hashed" varchar NOT NULL,
  "is_used" bool NOT NULL DEFAULT (false),
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "user_profile" (
  "user_id" bigint PRIMARY KEY NOT NULL,
  "basic_info" JSONB,
  "education" JSONB,
  "academic" JSONB,
  "test" JSONB,
  "internship" JSONB,
  "project" JSONB,
  "campus" JSONB,
  "award" JSONB,
  "liked_university" JSONB,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "refresh_token" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "user_id" bigint NOT NULL,
  "token_hashed" varchar(500) NOT NULL,
  "user_agent" varchar(100) NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "expire_at" timestamptz NOT NULL DEFAULT (now() + interval '30 days')
);

CREATE TABLE "passkey" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "credential_id" text UNIQUE NOT NULL,
  "public_key" text NOT NULL,
  "sign_count" bigint NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "last_used_at" timestamptz NOT NULL DEFAULT (now()),
  "is_active" bool NOT NULL DEFAULT (true)
);

CREATE TABLE "temp_token" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "user_id" bigint NOT NULL,
  "token_hashed" varchar(500) NOT NULL UNIQUE,
  "verification_code_hashed" varchar(500),
  "token_type" varchar(50) NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "expire_at" timestamptz NOT NULL
);

CREATE TABLE "university_program" (
  "id" varchar(36) PRIMARY KEY NOT NULL,
  "normalized_url" varchar(1000) UNIQUE,
  "normalized_name" varchar(1000) NOT NULL,
  "program_data" JSONB NOT NULL,
  "created_at" timestamptz DEFAULT (now()),
  "updated_at" timestamptz DEFAULT (now())
);

CREATE TABLE "user_liked_university" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "university_program_id" varchar(36) NOT NULL,
  "created_at" timestamptz DEFAULT (now())
);

CREATE INDEX ON "totp_backup_code" ("user_id", "is_used");

CREATE UNIQUE INDEX ON "refresh_token" ("token_hashed");

CREATE INDEX ON "refresh_token" ("user_id");

CREATE INDEX ON "refresh_token" ("expire_at");

CREATE UNIQUE INDEX ON "passkey" ("user_id", "credential_id");

CREATE INDEX ON "passkey" ("user_id", "is_active");

CREATE INDEX ON "temp_token" ("user_id", "expire_at");

CREATE INDEX ON "temp_token" ("token_hashed");

CREATE INDEX ON "temp_token" ("verification_code_hashed");

CREATE INDEX ON "temp_token" ("token_type");

CREATE UNIQUE INDEX ON "university_program" ("normalized_url");

CREATE INDEX ON "university_program" ("normalized_name");

CREATE UNIQUE INDEX ON "user_liked_university" ("user_id", "university_program_id");

COMMENT ON COLUMN "account"."user_name" IS 'User''s display name';

COMMENT ON COLUMN "account"."email" IS 'Emails are all in small cases';

COMMENT ON COLUMN "account"."user_type" IS '1=Student, 2=Institution, 99=Admin';

COMMENT ON COLUMN "account"."totp_secret_encrypted" IS 'use AES-GCM to encrypt, `not null` if 2FA is enabled';

COMMENT ON COLUMN "account"."updated_at" IS 'Auto-updated via trigger on UPDATE';

COMMENT ON COLUMN "account"."email_verified" IS 'Whether the user''s email has been verified';

COMMENT ON COLUMN "user_profile"."updated_at" IS 'Auto-updated via trigger on UPDATE';

COMMENT ON TABLE "refresh_token" IS 'Used as session store to validate login state by token';

COMMENT ON TABLE "temp_token" IS 'Used for temporary tokens like email verification, password reset, etc.';

COMMENT ON COLUMN "temp_token"."token_type" IS 'e.g., email_verify, password_reset, email_change';

COMMENT ON COLUMN "temp_token"."verification_code_hashed" IS 'Hashed verification code for flows that use a numeric/code verification (e.g., email/SMS). Stored hashed for security.';

COMMENT ON TABLE "university_program" IS 'Canonical deduplicated university program table.';

COMMENT ON COLUMN "university_program"."normalized_url" IS 'L1 dedup key: normalized official_program_url';

COMMENT ON COLUMN "university_program"."normalized_name" IS 'L2 dedup key: normalized university+program+degree';

COMMENT ON COLUMN "university_program"."program_data" IS 'Full program card JSON payload';

COMMENT ON TABLE "user_liked_university" IS 'Association table: user <-> liked university program';

ALTER TABLE "user_profile" ADD FOREIGN KEY ("user_id") REFERENCES "account" ("user_id") ON DELETE CASCADE;

ALTER TABLE "refresh_token" ADD FOREIGN KEY ("user_id") REFERENCES "account" ("user_id") ON DELETE CASCADE;

ALTER TABLE "totp_backup_code" ADD FOREIGN KEY ("user_id") REFERENCES "account" ("user_id") ON DELETE CASCADE;

ALTER TABLE "passkey" ADD FOREIGN KEY ("user_id") REFERENCES "account" ("user_id") ON DELETE CASCADE;

ALTER TABLE "temp_token" ADD FOREIGN KEY ("user_id") REFERENCES "account" ("user_id") ON DELETE CASCADE;

ALTER TABLE "user_liked_university" ADD FOREIGN KEY ("user_id") REFERENCES "account" ("user_id") ON DELETE CASCADE;

ALTER TABLE "user_liked_university" ADD FOREIGN KEY ("university_program_id") REFERENCES "university_program" ("id") ON DELETE CASCADE;
